### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by tacotexmex** [minetest-jp/midi-modpack#1]
I get OOM error after loading this modpack. Any ideas on how to solve it?

**Comment by Rui-Minetest** [comment]
Remove
- midi_instrument_salamander/sounds/midi_instrument_salamander_rel*.ogg
- midi_instrument_salamander/sounds/midi_instrument_salamander_harm*.ogg

Salamander piano has too many oggs, so they reduce memory area.

**Comment by tacotexmex** [comment]
Tried it but It wasn't enough. OOM still.

**Comment by Rui-Minetest** [comment]
Compressing ogg files
```bash
mv sounds/ sounds_pre/
for i in sounds_pre/*.ogg; do ffmpeg -i "$i" -c:a libvorbis -q:a 1 "sounds/$i"; done
```

If you get the error even after trying it or it's too much bother for you, use this alternative soundfont.
[midi_instrument_fm1.zip](https://github.com/minetest-jp/midi-modpack/files/3294060/midi_instrument_fm1.zip)

**Comment by tacotexmex** [comment]
That works, thanks!
